services:
    watcher:
        image: solar_watcher:latest
        build: 
          context: .
        restart: always
        volumes:
          - <<DEFINE>>:/opt/solarmax/etc
          - <<DEFINE>>:/opt/solarmax/log
    db:
        image: mariadb:12
        restart: always
        ports:
          - 127.0.0.1:3306:3306
        volumes:
          - <<DEFINE>>:/var/lib/mysql
        environment:
          MYSQL_DATABASE: '<<DEFINE>>'
          MYSQL_USER: '<<DEFINE>>'
          MYSQL_PASSWORD: '<<DEFINE>>'
          MYSQL_ROOT_PASSWORD: '<<DEFINE>>'
          TZ: 'Europe/Zurich'
